services:
  stat-db:
    image: postgres:16.1
    container_name: stat-postgres
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: ewm-stats
      POSTGRES_PASSWORD: ewm-stats
      POSTGRES_DB: ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
    volumes:
      - ./docker/postgres/stats.sql:/docker-entrypoint-initdb.d/01-stats.sql:ro

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: ewm-db
      POSTGRES_PASSWORD: ewm-db
      POSTGRES_DB: ewm-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
    volumes:
      - ./docker/postgres/main.sql:/docker-entrypoint-initdb.d/01-main.sql:ro
